### ISSUE TITLE
Pós Produção

### ISSUE THREAD

**Issue by PedroHLC** [bigarcia/ByteSurfer#8]

**Comment by bigarcia** [comment]
* [ ] Adicionar música à tela de de medalha (Pedro escolhe)
* [X] Verificar o final das músicas (blocos a mais)
* [ ] Remover linha de debug
* [ ] Rever todo o código
* Retirar musicas da pasta de envio para o professor
* [ ] Criar um link com a pasta inteira do jogo com a musica
* [X] Checar barulinho da janela do windows

**Comment by PedroHLC** [comment]
💥 Corrigi o bug dos blocos sobrando no final da música!
* [ ] Ajustar valores de pontuações máxima!
